[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["covid19_statistics_to_email_may2"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/ManualTrigger","Category/Integration"]
  name = "covid19_statistics_to_email_may2"
  org = "lakshansivagnanasothy"
  version = "3.1.1"

